version: "3.8"
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: moneydb
      POSTGRES_USER: moneyuser
      POSTGRES_PASSWORD: supersecret
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    environment:
      DATABASE_URL: postgresql://moneyuser:supersecret@db:5432/moneydb
      SECRET_KEY: yourSecretKey
      FLASK_ENV: development
    depends_on:
      - db
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app

  frontend:
    build: ./frontend
    environment:
      VITE_API_URL: http://backend:5000
    depends_on:
      - backend
    ports:
      - "3000:80"

volumes:
  postgres_data:
